name: "Deploy to GitHub Pages with Container"
description: "Container Action to Deploy to GitHub Pages"
author: "Max Held"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "upload-cloud"
  color: "blue"
