name: Deployment

"on":
  - push
  - pull_request

jobs:
  deploy_ghpages:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - run: echo $GITHUB_SHA >> public/index.html
      - uses: ./
        env:
          BUILD_DIR: public/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
